### ISSUE TITLE
oauth error

### ISSUE THREAD

**Issue by BrianTheCoder** [skorks/omniauth-linkedin#15]
I have configured the gem to work with omniauth and devise, however, when I try and authenticate I always get

```
OAuth::Problem (timestamp_refused)
```

**Comment by waaadim** [comment]
Just stumbled upon the same thing.
sign in with xing/linkedin works on my local machine, but only sign in with xing works on the server.
Any ideas on where to start looking for the issue ?

**Comment by waaadim** [comment]
the issue was that I didn't add the url in the linkedin app. "OAuth 2.0 Redirect URLs:"
